import {Phoneme} from "$lib/word/egyptian"
import {char, asum} from "crazy-parser"

export const pPhonemeEgyptology = asum(
	char("ꜥ").cmap(Phoneme.e),
	char("ẖ").cmap(Phoneme.C),
	char("ḥ").cmap(Phoneme.H),
	char("š").cmap(Phoneme.S),
	char("ꜣ").cmap(Phoneme.a),
	char("b").cmap(Phoneme.b),
	char("ṯ").cmap(Phoneme.c),
	char("d").cmap(Phoneme.d),
	char("f").cmap(Phoneme.f),
	char("g").cmap(Phoneme.g),
	char("h").cmap(Phoneme.h),
	char("ỉ").cmap(Phoneme.i),
	char("ḏ").cmap(Phoneme.j),
	char("k").cmap(Phoneme.k),
	char("m").cmap(Phoneme.m),
	char("n").cmap(Phoneme.n),
	char("p").cmap(Phoneme.p),
	char("ḳ").cmap(Phoneme.q),
	char("r").cmap(Phoneme.r),
	char("s").cmap(Phoneme.s),
	char("t").cmap(Phoneme.t),
	char("w").cmap(Phoneme.w),
	char("ḫ").cmap(Phoneme.x),
	char("y").cmap(Phoneme.y),
	char("z").cmap(Phoneme.z),
)

export const pPhonemeAscii = asum(
	char("a").cmap(Phoneme.a),
	char("i").cmap(Phoneme.i),
	char("y").cmap(Phoneme.y),
	char("e").cmap(Phoneme.e),
	char("w").cmap(Phoneme.w),
	char("b").cmap(Phoneme.b),
	char("p").cmap(Phoneme.p),
	char("f").cmap(Phoneme.f),
	char("m").cmap(Phoneme.m),
	char("n").cmap(Phoneme.n),
	char("r").cmap(Phoneme.r),
	char("h").cmap(Phoneme.h),
	char("H").cmap(Phoneme.H),
	char("x").cmap(Phoneme.x),
	char("C").cmap(Phoneme.C),
	char("s").cmap(Phoneme.s),
	char("z").cmap(Phoneme.z),
	char("S").cmap(Phoneme.S),
	char("k").cmap(Phoneme.k),
	char("g").cmap(Phoneme.g),
	char("q").cmap(Phoneme.q),
	char("t").cmap(Phoneme.t),
	char("c").cmap(Phoneme.c),
	char("d").cmap(Phoneme.d),
	char("j").cmap(Phoneme.j),
)
