export enum Glyph
{
	// Uniliteral (1 consonant)
	C_a = "𓄿",
	C_i = "𓇋",
	C_y = "𓇌",
	C_y_s = "𓏭",
	C_e = "𓂝",
	C_w = "𓅱",
	C_w_s = "𓏲",
	C_b = "𓃀",
	C_p = "𓊪",
	C_f = "𓆑",
	C_m = "𓅓",
	C_n = "𓈖",
	C_r = "𓂋",
	C_h = "𓉔",
	C_H = "𓎛",
	C_x = "𓐍",
	C_C = "𓄡",
	C_s = "𓋴",
	C_z = "𓊃",
	C_S = "𓈙",
	C_k = "𓎡",
	C_g = "𓎼",
	C_q = "𓈎",
	C_t = "𓏏",
	C_c = "𓍿",
	C_d = "𓂧",
	C_j = "𓆓",

	// Biliteral (2 consonants)
	C_ba = "𓅞",
	C_ib = "𓏋",
	C_jd = "𓊽",
	C_ka = "𓂓",
	C_ma = "𓌳",
	C_ms = "𓄠",
	C_nb = "𓎟",
	C_pr = "𓉐",
	C_re = "𓇳",
	C_st = "𓊨",
	C_sw = "𓇓",
	C_xa = "𓆼",

	// Triliteral (3 consonants)
	C_enx = "𓋹",
	C_mae = "𓐙",
	C_ncr = "𓊹",
	C_xrw = "𓊤",

	// Determinant
	D_bee = "𓆤",
	D_city = "𓊖",
	D_identity = "𓏤",
	D_earth = "𓇾",
	D_papyrus = "𓏛",
	D_plural = "𓏥",

	// Ligature
	L_voice_offering = "𓉓",

	// Numeric
}

// N_1 = "𓏺",
// N_2 = "𓏻",
// N_3 = "𓏼",
// N_4 = "𓏽",
// N_5 = "𓏾",
// N_6 = "𓏿",
// N_7 = "𓐀",
// N_8 = "𓐁",
// N_9 = "𓐂",
// N_10 = "𓎆",
// N_20 = "𓎇",
// N_30 = "𓎈",
// N_40 = "𓎉",
// N_50 = "𓎊",
// N_60 = "𓎋",
// N_70 = "𓎌",
// N_80 = "𓎍",
// N_90 = "𓎎",
// N_100 = "𓍢",
// N_200 = "𓍣",
// N_300 = "𓍤",
// N_400 = "𓍥",
// N_500 = "𓍦",
// N_600 = "𓍧",
// N_700 = "𓍨",
// N_800 = "𓍩",
// N_900 = "𓍪",
// N_1000 = "𓆼",
// N_2000 = "𓆽",
// N_3000 = "𓆾",
// N_4000 = "𓆿",
// N_5000 = "𓇀",
// N_6000 = "𓇁",
// N_7000 = "𓇂",
// N_8000 = "𓇃",
// N_9000 = "𓇄",
// N_10000 = "𓂭",
// N_20000 = "𓂮",
// N_30000 = "𓂯",
// N_40000 = "𓂰",
// N_50000 = "𓂱",
// N_60000 = "𓂲",
// N_70000 = "𓂳",
// N_80000 = "𓂴",
// N_90000 = "𓂵",

export const GlyphToGardiner: Record<Glyph, string> = {
	[Glyph.C_a]: "G1",
	[Glyph.C_i]: "M17",
	[Glyph.C_y]: "M17A",
	[Glyph.C_y_s]: "Z4",
	[Glyph.C_e]: "𓂝",
	[Glyph.C_w]: "𓅱",
	[Glyph.C_w_s]: "𓏲",
	[Glyph.C_b]: "𓃀",
	[Glyph.C_p]: "𓊪",
	[Glyph.C_f]: "𓆑",
	[Glyph.C_m]: "𓅓",
	[Glyph.C_n]: "𓈖",
	[Glyph.C_r]: "𓂋",
	[Glyph.C_h]: "𓉔",
	[Glyph.C_H]: "𓎛",
	[Glyph.C_x]: "𓐍",
	[Glyph.C_C]: "𓄡",
	[Glyph.C_s]: "𓋴",
	[Glyph.C_z]: "𓊃",
	[Glyph.C_S]: "𓈙",
	[Glyph.C_k]: "𓎡",
	[Glyph.C_g]: "𓎼",
	[Glyph.C_q]: "𓈎",
	[Glyph.C_t]: "𓏏",
	[Glyph.C_c]: "𓍿",
	[Glyph.C_d]: "𓂧",
	[Glyph.C_j]: "𓆓",
	[Glyph.C_ba]: "𓅞",
	[Glyph.C_ib]: "𓏋",
	[Glyph.C_jd]: "𓊽",
	[Glyph.C_ka]: "𓂓",
	[Glyph.C_ma]: "𓌳",
	[Glyph.C_ms]: "𓄠",
	[Glyph.C_nb]: "𓎟",
	[Glyph.C_pr]: "𓉐",
	[Glyph.C_re]: "𓇳",
	[Glyph.C_st]: "𓊨",
	[Glyph.C_sw]: "𓇓",
	[Glyph.C_xa]: "𓆼",
	[Glyph.C_enx]: "𓋹",
	[Glyph.C_mae]: "𓐙",
	[Glyph.C_ncr]: "𓊹",
	[Glyph.C_xrw]: "𓊤",
	[Glyph.D_bee]: "𓆤",
	[Glyph.D_city]: "𓊖",
	[Glyph.D_identity]: "𓏤",
	[Glyph.D_earth]: "𓇾",
	[Glyph.D_papyrus]: "𓏛",
	[Glyph.D_plural]: "𓏥",
	[Glyph.L_voice_offering]: "𓉓",
}

export default Glyph
